enable:
  issues: true
  prs: true

labels:
  bug:
    include:
      - '\bbug(?:\(.+\))?\b'
  chore:
    include:
      - '\bchore(?:\(.+\))?\b'
  docs:
    include:
      - '\bdocs(?:\(.+\))?\b'
  feat:
    include:
      - '\bfeat(?:\(.+\))?\b'
  fix:
    include:
      - '\bfix(?:\(.+\))?\b'
  refactor:
    include:
      - '\brefactor(?:\(.+\))?\b'
  style:
    include:
      - '\bstyle(?:\(.+\))?\b'
