import { styleVariants } from '@vanilla-extract/css';
import { vars } from '../../vars.css';

export const backgroundColor = styleVariants({
  archiveBlack: { backgroundColor: vars.color.archive.black },
  archiveBlue: { backgroundColor: vars.color.archive.blue },
  archiveBrightGreen: { backgroundColor: vars.color.archive.brightGreen },
  archiveCoral: { backgroundColor: vars.color.archive.coral },
  archiveMint: { backgroundColor: vars.color.archive.mint },
  archivePink: { backgroundColor: vars.color.archive.pink },
  archivePurple: { backgroundColor: vars.color.archive.purple },
  archiveYellow: { backgroundColor: vars.color.archive.yellow },
  gray100: { backgroundColor: vars.color.gray[100] },
  gray200: { backgroundColor: vars.color.gray[200] },
  gray300: { backgroundColor: vars.color.gray[300] },
  gray400: { backgroundColor: vars.color.gray[400] },
  gray500: { backgroundColor: vars.color.gray[500] },
  gray600: { backgroundColor: vars.color.gray[600] },
  gray700: { backgroundColor: vars.color.gray[700] },
  gray800: { backgroundColor: vars.color.gray[800] },
  gray900: { backgroundColor: vars.color.gray[900] },
  gray1000: { backgroundColor: vars.color.gray[1000] },
  gray1100: { backgroundColor: vars.color.gray[1100] },
  system100: { backgroundColor: vars.color.system[100] },
  system200: { backgroundColor: vars.color.system[200] },
  system300: { backgroundColor: vars.color.system[300] },
  repoTextBlack: { backgroundColor: vars.color.repo.text.black },
  repoTextBlue: { backgroundColor: vars.color.repo.text.blue },
  repoTextBrightGreen: { backgroundColor: vars.color.repo.text.brightGreen },
  repoTextCoral: { backgroundColor: vars.color.repo.text.coral },
  repoTextMint: { backgroundColor: vars.color.repo.text.mint },
  repoTextPink: { backgroundColor: vars.color.repo.text.pink },
  repoTextPurple: { backgroundColor: vars.color.repo.text.purple },
  repoTextYellow: { backgroundColor: vars.color.repo.text.yellow },
  repoBgBlack: { backgroundColor: vars.color.repo.bg.black },
  repoBgBlue: { backgroundColor: vars.color.repo.bg.blue },
  repoBgBrightGreen: { backgroundColor: vars.color.repo.bg.brightGreen },
  repoBgCoral: { backgroundColor: vars.color.repo.bg.coral },
  repoBgMint: { backgroundColor: vars.color.repo.bg.mint },
  repoBgPink: { backgroundColor: vars.color.repo.bg.pink },
  repoBgPurple: { backgroundColor: vars.color.repo.bg.purple },
  repoBgYellow: { backgroundColor: vars.color.repo.bg.yellow },
});
