import {
  bottom,
  bottomVar,
  flexBasis,
  flexBasisVar,
  flexGrow,
  flexShrink,
  height,
  heightVar,
  inset,
  insetVar,
  left,
  leftVar,
  maxHeight,
  maxHeightVar,
  maxWidth,
  maxWidthVar,
  minHeight,
  minHeightVar,
  minWidth,
  minWidthVar,
  overflow,
  overflowX,
  overflowY,
  padding,
  paddingBottom,
  paddingBottomVar,
  paddingLeft,
  paddingLeftVar,
  paddingRight,
  paddingRightVar,
  paddingTop,
  paddingTopVar,
  paddingVar,
  paddingX,
  paddingXVar,
  paddingY,
  paddingYVar,
  position,
  right,
  rightVar,
  top,
  topVar,
  width,
  widthVar,
} from '@favolink-ui/styles';
import { type RecipeVariants, recipe } from '@vanilla-extract/recipes';

export const boxEnumVariants = recipe({
  variants: {
    position,
    overflow,
    overflowX,
    overflowY,
    flexShrink,
    flexGrow,
  },
});

export type BoxEnumVariants = Exclude<
  RecipeVariants<typeof boxEnumVariants>,
  undefined
>;

export const boxDynamicVariantVars = {
  paddingVar,
  paddingBottomVar,
  paddingLeftVar,
  paddingRightVar,
  paddingTopVar,
  paddingXVar,
  paddingYVar,
  widthVar,
  minWidthVar,
  maxWidthVar,
  heightVar,
  minHeightVar,
  maxHeightVar,
  insetVar,
  topVar,
  bottomVar,
  leftVar,
  rightVar,
  flexBasisVar,
};

export const boxDynamicVariants = {
  padding,
  paddingBottom,
  paddingLeft,
  paddingRight,
  paddingTop,
  paddingX,
  paddingY,
  width,
  minWidth,
  maxWidth,
  height,
  minHeight,
  maxHeight,
  inset,
  top,
  bottom,
  left,
  right,
  flexBasis,
};

export type BoxDynamicVariants = Partial<
  Record<keyof typeof boxDynamicVariants, number | string>
>;
