name: CI

on:
  push:
    branches:
      - main

  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check-quality:
    timeout-minutes: 15

    runs-on: ubuntu-latest

    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    strategy:
      matrix:
        command: [lint, build]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm package manager
        uses: pnpm/action-setup@v3
        with:
          run_install: false

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
          node-version-file: .nvmrc

      - name: Install dependencies
        run: pnpm install

      - name: Run commands
        run: pnpm ${{ matrix.command }}
