name: Project

on:
  issues:
    types: [opened]

  pull_request:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/dnd-side-project/projects/71
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
